### PR TITLE
Fixed the orphaned node bug

### LINKED ISSUE #344: Fetching some data without an id and then with an id results in an orphaned node in the cache
Because we re-point the root query path to the node dataId, but don't move the previously fetched data with a generated ID.

### PR DESCRIPTION
**Pull request by Poincare**
Fixes #344.

TODO:

- [ ] Update CHANGELOG.md with your change
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by Poincare** [comment]
@stubailo Should be ready for review.

File: src/data/writeToStore.ts [hunk 1]
```diff
@@ -195,6 +195,31 @@ export function writeSelectionSetToStore({
...
+// rather than by dataIdFromObject.
+function isGeneratedId(id: string): boolean {
+  return (id[0] === '$');
+}
+
+function mergeWithGenerated(generatedKey: string, realKey: string, cache: NormalizedCache) {
+  const generated = cache[generatedKey];
+  const real = cache[realKey];
+
+  if (typeof generated !== 'object' || typeof real !== 'object') {
```
Comment (stubailo) [inline src/data/writeToStore.ts]: I'm not sure what this is trying to check, since `object` is also the type of `null`, `Array`, etc. Perhaps we should use `isObject`?

File: src/data/writeToStore.ts [hunk 2]
```diff
@@ -195,6 +195,31 @@ export function writeSelectionSetToStore({
...
+    return;
+  }
+  Object.keys(generated).forEach((key) => {
+    const value = generated[key];
+    if (typeof value === 'string'
```
Comment (stubailo) [inline src/data/writeToStore.ts]: Again here, let's use `isString`. I don't really trust `typeof` tbh.

File: src/data/writeToStore.ts [hunk 3]
```diff
@@ -255,10 +282,21 @@ function writeFieldToStore({
   } else {
     // It's an object
     let valueDataId = `${dataId}.${storeFieldName}`;
+    if (!isGeneratedId(valueDataId)) {
```
Comment (stubailo) [inline src/data/writeToStore.ts]: I'd add a comment here - I guess this if statement is because `dataId` might already be generated.

File: src/data/writeToStore.ts [hunk 4]
```diff
@@ -275,11 +313,23 @@ function writeFieldToStore({
     });
 
     storeValue = valueDataId;
+
+    // check if there was a generated id at the location where we're
+    // about to place this new id. If there was, we have to merge the
+    // data from that id with the data we're about to write in the store.
+    if (store[dataId] && store[dataId][storeFieldName] !== storeValue) {
```
Comment (stubailo) [inline src/data/writeToStore.ts]: I feel like `store[dataId][storeFieldName]` needs to be factored out into a variable with some semantic name.

**Comment by Poincare** [comment]
Fixed @stubailo

File: src/data/writeToStore.ts [hunk 5]
```diff
@@ -195,6 +197,31 @@ export function writeSelectionSetToStore({
...
+function isGeneratedId(id: string): boolean {
+  return (id[0] === '$');
+}
+
+function mergeWithGenerated(generatedKey: string, realKey: string, cache: NormalizedCache) {
+  const generated = cache[generatedKey];
+  const real = cache[realKey];
+
+  if (!isObject(generated) || !isObject(real)) {
+    return;
```
Comment (stubailo) [inline src/data/writeToStore.ts]: I feel that this should throw an error rather than silently failing, since this condition should never happen.

Comment (Poincare) [inline src/data/writeToStore.ts]: This condition could happen if you have a particular key like "name" that has a value that looks like "$David" or something similar, i.e. this error could happen if the data returned by the server uses a `$` sign in a particular way. I don't think the client should impose restrictions on the data returned so I guess it makes sense to silently ignore that issue.

File: src/data/writeToStore.ts [hunk 6]
```diff
@@ -195,6 +197,31 @@ export function writeSelectionSetToStore({
...
+  }
+  Object.keys(generated).forEach((key) => {
+    const value = generated[key];
+    if (isString(value)
+        && isGeneratedId(value)
```
Comment (stubailo) [inline src/data/writeToStore.ts]: This should check if there is a subselection on the query, rather than trying to identify IDs by checking for strings that start with `$`.

**Comment by Poincare** [comment]
After some discussion, @stubailo and I decided that we should incorporate #410 into this PR so I'll implement that now

**Comment by Poincare** [comment]
@Slava One of the optimistic UI tests is failing once I rebased but I'm not sure why - could you take a look?

**Comment by Poincare** [comment]
Fixed the test thanks to @Slava. @stubailo ready for review

File: src/data/diffAgainstStore.ts [hunk 7]
```diff
@@ -269,9 +272,17 @@ Perhaps you want to use the \`returnPartialData\` option?`);
 
   // Handle all scalar types here
   if (! field.selectionSet) {
-    return {
-      result: storeValue,
-    };
+    if (!isJsonValue(storeValue)) {
```
Comment (stubailo) [inline src/data/diffAgainstStore.ts]: I'd prefer to reorder these, so that we don't need the `!`. Then we also don't need the cast since TypeScript can figure out the types for us I think.

File: src/data/diffAgainstStore.ts [hunk 8]
```diff
@@ -315,18 +326,21 @@ Perhaps you want to use the \`returnPartialData\` option?`);
...
-      rootId: storeValue,
+      rootId: unescapedId,
       selectionSet: field.selectionSet,
       variables,
       fragmentMap,
     });
   }
 
-  throw new Error('Unexpected number value in the store where the query had a subselection.');
+  throw new Error('Unexpected value in the store where the query had a subselction.');
```
Comment (stubailo) [inline src/data/diffAgainstStore.ts]: Typo - subselection

File: src/data/diffAgainstStore.ts [hunk 9]
```diff
@@ -315,18 +326,21 @@ Perhaps you want to use the \`returnPartialData\` option?`);
     };
   }
 
-  if (isString(storeValue)) {
+  // If the store value is an object and it has a selection set, it must be
+  // an escaped id.
+  if (isIdValue(storeValue)) {
+    const unescapedId = (storeValue as IdValue).id;
```
Comment (stubailo) [inline src/data/diffAgainstStore.ts]: Do we need this cast? Do TypeScript type guards not work anymore?

File: src/data/writeToStore.ts (hunk 4 above)
Comment (stubailo) [inline src/data/writeToStore.ts]: This comment still stands

File: test/QueryManager.ts [hunk 10]
```diff
@@ -564,10 +564,10 @@ describe('QueryManager', () => {
         result: { data: data2 },
       }
     );
-
+    const store = createApolloStore();
```
Comment (stubailo) [inline test/QueryManager.ts]: Why this change?

File: test/QueryManager.ts [hunk 11]
```diff
@@ -2778,6 +2822,202 @@ describe('QueryManager', () => {
...
+    setTimeout(() => {
+      assert.equal(resultsReceived1, 1);
+      assert.equal(resultsReceived2, 1);
+      assert.equal(errorsReceived1, 1);
+      done();
+    }, 60);
+  });
+
+
+  it('should not error when we orphan a no-id node in the store with a real-id node', (done) => {
```
Comment (stubailo) [inline test/QueryManager.ts]: This is not an accurate description, right? Since we aren't actually orphaning anything, we are rewriting the previous ID?

Also, can we add a test where something first had a real ID, and then it has a generated ID? In that case we should keep the real ID.

**Comment by stubailo** [comment]
A few small comments, but one thing I'd really like to see is an example where a query with no id gets written to a store that already has a real ID.

**Comment by Poincare** [comment]
@stubailo fixed
