### PR TITLE
[WIP] Fix issues with fragments (inline + spread) (union types + @skip/@include)

### LINKED ISSUE #354: Fragmenting on a Union type will throw when storing the result to state
Given this GraphQL Schema:
```
type RootQueryType {
  fruitList: [Fruits]
}

union Fruits = Apple | Orange

type Apple {
  color: String
}

type Orange {
  weight: Int
}
```

And this query:
```GraphQL
fruitList {
  ... on Apple {
    color
  }
  ... on Orange {
    weight
  }
}
```

And this server response:
```
{
  fruitlist: [
    {
      __typename: 'Apple',
      color: 'Red'
    }
  ]
}
```

The client will throw at [this line](https://github.com/apollostack/apollo-client/blob/master/src/data/writeToStore.ts#L145), claiming it's missing the "weight" property. In this case the client should ignore the "weight" property since the returned object is of type `Apple`.

### LINKED ISSUE #355: Fragmenting with @skip and @include directives will throw when storing the result to state
Very likely correlated to #354.

Given this kind of query:

```graphql
a_fruit {
  ... on Apple @include(if: $selectApples) {
    color
  }
  ... on Orange @include(if: $selectOranges) {
    weight
  }
}
```

With this server response:

```graphql
{
  a_fruit: {
      color: 'Red'
  }
}
```

The client will throw a missing the "weight" property. In this case the client should ignore the "weight" property since the weight has not been included.

Note that changing the query to this solves the issue:

```graphql
a_fruit {
  ... on Apple @include(if: $selectApples) {
    color @include(if: $selectApples)
  }
  ... on Orange @include(if: $selectOranges) {
    weight @include(if: $selectOranges)
  }
}
```

### PR DESCRIPTION
**Pull request by rricard**
- [x] Test case for #354 
- [x] Test case for #355
- [x] Fix #354
- [x] Fix #355
- [x] Test case for fragment spreads
- [x] Test failing two inline frags of the same type
- [x] Fix for fragment spreads (#361)

### CODE REVIEW

**Comment by stubailo** [comment]
These would be much simpler to test here: https://github.com/apollostack/apollo-client/blob/master/test/roundtrip.ts

These tests basically just check that a query can travel through the store unchanged, which is what I think we are trying to do here.

**Comment by rricard** [comment]
@stubailo I'll try that, thanks!

**Comment by rricard** [comment]
Ok, now going into debug mode 🔴 ➡️

**Comment by Poincare** [comment]
I think this shouldn't be too hard to fix. Right now, `src/writeSelectionSetToStore` is called recursively on the entire document AST. The solution should consist of not running it recursively on stuff that's been skipped (e.g. skipped inline fragments).

**Comment by Poincare** [comment]
Looks cool to me! I think the same issue (i.e. #355) will also apply to fragment spreads (i.e. anything we have to recurse on) because it will try to look for those fields as well even if they've been skipped.  Basically, we should only recurse in any capacity if the `skip` evaluates to false.

File: src/data/writeToStore.ts [hunk 1]
```diff
@@ -161,16 +162,19 @@ export function writeSelectionSetToStore({
...
+          result,
+          selectionSet: selection.selectionSet,
+          store,
+          variables,
+          dataId,
+          dataIdFromObject,
+          fragmentMap,
+        });
+      }
     } else {
```
Comment (Poincare) [inline src/data/writeToStore.ts]: The same issue will apply to fragment spreads which are processed inside this `else` block so applying the same idea here should work as well. We should probably introduce a unit test for named fragments as well - should be exactly the same as the inline fragment test just with fragment names.

Comment (rricard) [inline src/data/writeToStore.ts]: Ok, I'll take a look at that, thanks for pointing it out!

**Comment by rricard** [comment]
@Poincare & @stubailo : I'm not sure fragment spreads works in `roundtrip.js`. Is this normal ? Should I move the fragment spread tests elsewhere ?

File: src/data/diffAgainstStore.ts [hunk 2]
```diff
@@ -158,49 +161,69 @@ export function diffSelectionSetAgainstStore({
...
+          }
+          fragmentErrors.push(false);
+        } catch (e) {
+          fragmentErrors.push(e);
+        }
       }
     }
   });
 
+  if (fragmentErrors.length > 0 && fragmentErrors.filter(e => !e).length === 0) {
```
Comment (Poincare) [inline src/data/diffAgainstStore.ts]: I don't think this will work if we have multiple fragments that affect a single type and only one of them throws an error. That will result in this not throwing an error when it should.

**Comment by Poincare** [comment]
@rricard You're right - it seems that named fragments don't currently work in `roundtrip.ts`. I've filed an issue about that at #361. In the meantime, we can just move those tests to `test/QueryManager.ts`, I think.

File: src/data/diffAgainstStore.ts (hunk 2 above)
Comment (rricard) [inline src/data/diffAgainstStore.ts]: You're right, however, I prefer exploiting a try/catch still so I avoid passing around a complex structure.

**Comment by rricard** [comment]
Or I could just try to fix #361 as well. I didn't get into any details but that doesn't seem to hard...

**Comment by rricard** [comment]
@Poincare, all done!

**Comment by rricard** [comment]
Maybe wait for #350 to be merged first. Rebasing this one will be "cheaper" than rebasing the other.

**Comment by Poincare** [comment]
Looks great to me + ready to merge! I think holding off on merging until we have #350 sorted out makes sense.

File: test/roundtrip.ts [hunk 3]
```diff
@@ -109,19 +113,176 @@ describe('roundtrip', () => {
...
+          },
+          {
+            name: 'R2D2',
+            model: 'astromech',
+          },
+        ],
+      });
+    });
+
+    it('should throw on error on two of the same spread fragment types', () => {
```
Comment (stubailo) [inline test/roundtrip.ts]: I don't think this should throw an error - don't people use multiple fragments on one type like all the time?

Comment (Poincare) [inline test/roundtrip.ts]: The intention is to throw the error if fields in either one of the fragments are missing. Here, the "rank" field is not present.

File: src/data/diffAgainstStore.ts [hunk 4]
```diff
@@ -132,75 +133,106 @@ export function diffSelectionSetAgainstStore({
...
+        } catch (e) {
+          fragmentErrors[typeName] = e;
+        }
       }
     }
   });
 
+  const errors = Object.keys(fragmentErrors).map(type => fragmentErrors[type]);
+  if (errors.length > 0 && errors.filter(err => !!err).length === errors.length) {
+    throw errors.some(err => !!err);
```
Comment (stubailo) [inline src/data/diffAgainstStore.ts]: What's the goal of this line of code? Right now, it just throws `true`.

Comment (stubailo) [inline src/data/diffAgainstStore.ts]: I added some failing tests about it.

Comment (rricard) [inline src/data/diffAgainstStore.ts]: whoups, my bad! Wanted to use `.find` instead.

**Comment by rricard** [comment]
**WARNING: Rebased**

File: test/roundtrip.ts (hunk 3 above)
Comment (rricard) [inline test/roundtrip.ts]: This is now clearer with the error message tests.

**Comment by stubailo** [comment]
Woohoo finally got this in!
