### PR TITLE
Fix query alias batching issue

### LINKED ISSUE #490: Renaming queries not working with batching
If I send the following query in a request that is batched with other queries...

```
query getActivity {
  activities: lookActivities(skip: 0, limit: 10) {
    _id
    type
    owner {
      _id
      name
    }
  }
}
```
...it will give me the following error:

image

However, if it isn't batched with other queries, it will work fine. It will also work fine if I don't rename the query:
```
query getActivity {
  lookActivities(skip: 0, limit: 10) {
    _id
    type
    owner {
      _id
      name
    }
  }
}
```

### PR DESCRIPTION
**Pull request by Poincare**
Fixes #490. 

TODO:

- [x] Update CHANGELOG.md with your change
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

File: src/batching/queryMerging.ts [hunk 1]
```diff
@@ -96,7 +96,12 @@ export function unpackMergedResult(result: GraphQLResult,
     const childRequestIndex = mergeInfo.requestIndex;
     const fieldMap = fieldMaps[childRequestIndex];
     const field = fieldMap[mergeInfo.fieldIndex];
-    data[field.name.value] = result.data[dataKey];
+
+    // If this field has been aliased, then we need the alias name
+    // (as opposed to the field name) as the key of the result
+    // structure that we return.
+    const keyName = field.alias ? field.alias.value : field.name.value;
```
Comment (stubailo) [inline src/batching/queryMerging.ts]: `resultKeyNameFromField` in `storeUtils` already does this.

Comment (Poincare) [inline src/batching/queryMerging.ts]: Fixed @stubailo
