### PR TITLE
Pass errors to handler function in network interface

### LINKED ISSUE #33: Network interface should return errors object in promise rejection
Currently, this code in QueryManager:

```ts
    this.networkInterface.query([
      request,
    ]).then((result) => {
      const resultWithDataId = assign({
        __data_id: 'ROOT_QUERY',
      }, result[0].data);

      this.store.dispatch(createQueryResultAction({
        result: resultWithDataId,
        selectionSet: queryDef.selectionSet,
      }));
    }).catch((errors: GraphQLError[]) => {
      this.handleQueryErrorsAndStop(watchHandle.id, errors);
    });
```

Doesn't work! Because `catch` actually gets a string with some serialized errors. We need it to return the actual error data.

### PR DESCRIPTION
**Pull request by jbaxleyiii**
This fixes #33 

A GraphQL server can respond back to a query with both data and errors. The network interface does not currently handle that.

```
interface GraphQLResult {
  data?: Object;
  errors?: Array<GraphQLError>;
}
````

@stubailo how do you want me to handle this? If the result has data I can pass it back as a `<GraphQLResult>` and the query manager can split the data up?

### CODE REVIEW

File: src/networkInterface.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export function createNetworkInterface(uri: string, opts: RequestInit = {}): Net
     }));
   };
 
-  function query(requests: Array<Request>): Promise<Array<GraphQLResult>> {
+  function query(requests: Array<Request>): Promise<Array<GraphQLResult | GraphQLError>> {
     let clonedRequests = [...requests];
```
Comment (mquandalle) [inline src/networkInterface.ts]: Is cloning needed here?

Comment (jbaxleyiii) [inline src/networkInterface.ts]: nope! It was from an earlier iteration!

File: src/QueryManager.ts [hunk 2]
```diff
@@ -110,6 +111,25 @@ export class QueryManager {
...
+      results = results.map((x: GraphQLResult) => {
+        if (x.errors && x.errors.length) {
+          errors = errors.concat(x.errors);
+        }
+
+        return { data: x.data };
+      });
+
+      if (errors.length) {
+        this.handleQueryErrorsAndStop(watchHandle.id, errors);
```
Comment (jbaxleyiii) [inline src/QueryManager.ts]: Since this throws, is this really even helpful? should it not throw in this case? Either way we should add a test to verify handling of mixed data

**Comment by stubailo** [comment]
Hmm, yeah I'm thinking based on just talking with @helfer that we should support the case where both an error and data are returned. I propose unifying the `onData` and `onError` callbacks into something like `onResult((errors, data) => ...)`. What do you think? Then we should basically not use the `catch` part of the promise, and just return it as a result no matter what. Perhaps we should throw on a network error, and then handle that in the query manager?

File: src/QueryManager.ts [hunk 3]
```diff
@@ -110,6 +111,25 @@ export class QueryManager {
     this.networkInterface.query([
       request,
     ]).then((result) => {
+      let errors: GraphQLError[] = [];
+      let results: GraphQLResult[] = [...result];
+
+      // pick errors off of mixed errors and data objects so they
+      // can be handled without blocking the good data
+      // that did come through
+      results = results.map((x: GraphQLResult) => {
```
Comment (stubailo) [inline src/QueryManager.ts]: This part of the code assumes that there is only one query? Seems like multiple queries, and consequently multiple results/errors, would be part of the implementation of a batching feature, rather than in this PR.

**Comment by jbaxleyiii** [comment]
@stubailo in that case I'll remove `Requests[]` and instead merge `_query` and `query to only accept one request at a time. I'll always return if `data` is present and if there is no data and just error (e.g. a syntax error on the request), throw the exception and the catch method can handle it?

**Comment by stubailo** [comment]
> I'll always return if data is present and if there is no data and just error (e.g. a syntax error on the request), throw the exception and the catch method can handle it?

If possible I think it would be best to always `resolve` in the case of a GraphQL error (something was returned, with an `errors` field in the response), and `reject` in the case of a network error. That way it will be more predictable which callbacks are called when.

**Comment by jbaxleyiii** [comment]
Can do! I'll do that today

**Comment by jbaxleyiii** [comment]
@stubailo would you mind taking a look at this now? I *think* its inline with what you were thinking. We currently still err out on errors which I don't think is ideal.

Should we store the errors alongside the data in the store somewhere?

**Comment by stubailo** [comment]
Yeah, I think this is a good start. I don't know how much we want to nitpick over this one PR vs. merging it and starting some new ones. I think this is a great start and we can merge it now.

Here's what I would do next (probably in future PRs):

1. Store the error in the store (what's the best practice for this in Redux? people must already have figured this out)
2. Have a mechanism for handling network errors rather than just throwing with an error message
3. Put back the functionality to fetch multiple queries at once, which we might need once batching is a thing in #25

**Comment by jbaxleyiii** [comment]
@stubailo :+1: I can' quickly put back handling multiple queries as once pretty quickly but I was imagining the batching actually combining the request into a single operation fwiw. 

I removed the multiple queries because of this: 
> This part of the code assumes that there is only one query? Seems like multiple queries, and consequently multiple results/errors, would be part of the implementation of a batching feature, rather than in this PR.

but I may have misunderstood :)

**Comment by stubailo** [comment]
I think we're on the same page. Let's merge this and then decide how we want to do batching later. If batching doesn't require multiple operations in one request, then we can safely not have that feature in our network interface for now.
